alter TABLE USUARIO add column ENDERECO_ID BIGINT not null;

ALTER TABLE USUARIO ADD CONSTRAINT ENDERECO_ID_FK FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID);

ALTER TABLE ENDERECO DROP FOREIGN KEY ENDERECO_USUARIO_ID_FK;
ALTER TABLE ENDERECO DROP COLUMN USUARIO_ID;
