-- CREATE COLUM
CREATE TABLE COZINHA(
ID BIGINT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(70) NOT NULL,

PRIMARY KEY (ID)
) engine=InnoDB default charset=utf8;

CREATE TABLE USUARIO(
ID BIGINT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(70) NOT NULL,
DDD VARCHAR(3) NOT NULL,
TELEFONE VARCHAR(30) NOT NULL,

PRIMARY KEY (ID)
)engine=InnoDB default charset=utf8;


CREATE TABLE ENDERECO(
ID BIGINT NOT NULL AUTO_INCREMENT,
CEP VARCHAR(14) NOT NULL,
NUMERO BIGINT NOT NULL,
COMPLEMENTO VARCHAR(100),
USUARIO_ID BIGINT NOT NULL,

PRIMARY KEY (ID)
)engine=InnoDB default charset=utf8;

ALTER TABLE ENDERECO ADD CONSTRAINT ENDERECO_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

CREATE TABLE PAGAMENTO(
ID BIGINT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(100) NOT NULL,

PRIMARY KEY (ID)
)engine=InnoDB default charset=utf8;


CREATE TABLE RESTAURANTE(
ID BIGINT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(70) NOT NULL,
TAXA_FRETE DECIMAL NOT NULL,
COZINHA_ID BIGINT NOT NULL,

PRIMARY KEY (ID)
)engine=InnoDB default charset=utf8;

ALTER TABLE RESTAURANTE ADD CONSTRAINT COZINHA_ID_FK FOREIGN KEY (COZINHA_ID) REFERENCES COZINHA (ID);

